#!/usr/bin/python3
# -*- coding: utf-8 -*-
import timeit
temps1=-1
temps2=-1
temps3=-1

@@q1@@ 


def benchmark():
    temps1 = timeit.timeit("est_premier_1(101)",setup="from student import est_premier_1",number=100000)
    temps2 = timeit.timeit("est_premier_2(101)",setup="from student import est_premier_2",number=100000)
    temps3 = timeit.timeit("est_premier_3(101)",setup="from student import est_premier_3",number=100000)
    return temps1,temps2,temps3

def fonction():
    
    return benchmark()