#!/usr/bin/python3
# -*- coding: utf-8 -*-


def forbid_max(a, *b):
    raise AttributeError(("Nice try! But built-in 'maxc' function has been disabled.\n"
                         "\t\tPlease write an actual algorithm returning the maximum of the 2 values."))

max = forbid_max

@@q1@@
